//! Software GOST R 34.10-2012 elliptic-curve arithmetic over a prime field in
//! short Weierstrass form `y^2 = x^3 + a*x + b (mod p)`.
//!
//! This is the minimal EC layer needed for the RFC 9189 CNT_IMIT key transport:
//! an **ephemeral** key pair is generated on the *server's* curve and a
//! Diffie-Hellman shared point is computed with VKO (see [`crate::gost_vko`]).
//! The cofactor of every GOST curve used here is 1 (`m == q`), so cofactor
//! multiplication is the identity and is omitted.
//!
//! Coordinates and scalars are [`BigUint`]. GOST stores curve points and keys
//! **little-endian**; helpers convert between that wire form and the integers
//! used for the math.

use num_bigint::BigUint;
use num_integer::Integer;
use num_traits::{One, Zero};

/// A prime-field short-Weierstrass curve with a generator of prime order `q`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Curve {
    /// Field characteristic (prime modulus).
    pub p: BigUint,
    /// Curve coefficient `a`.
    pub a: BigUint,
    /// Curve coefficient `b`.
    pub b: BigUint,
    /// Order of the cyclic subgroup generated by `(gx, gy)`.
    pub q: BigUint,
    /// Generator x-coordinate.
    pub gx: BigUint,
    /// Generator y-coordinate.
    pub gy: BigUint,
    /// Coordinate size in bytes (field element width on the wire).
    pub field_bytes: usize,
}

/// An affine point on a [`Curve`], or the point at infinity.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Point {
    /// The identity element.
    Infinity,
    /// An affine point `(x, y)`.
    Affine { x: BigUint, y: BigUint },
}

#[inline]
fn mod_add(a: &BigUint, b: &BigUint, p: &BigUint) -> BigUint {
    (a + b) % p
}

#[inline]
fn mod_sub(a: &BigUint, b: &BigUint, p: &BigUint) -> BigUint {
    // a, b are already reduced mod p; compute (a - b) mod p without going negative.
    let a = a % p;
    let b = b % p;
    if a >= b { a - b } else { (a + p) - b }
}

#[inline]
fn mod_mul(a: &BigUint, b: &BigUint, p: &BigUint) -> BigUint {
    (a * b) % p
}

/// Modular inverse via Fermat's little theorem (`p` is prime): `a^(p-2) mod p`.
#[inline]
fn mod_inv(a: &BigUint, p: &BigUint) -> BigUint {
    let exp = p - 2u32;
    a.modpow(&exp, p)
}

impl Curve {
    /// Construct a curve from already-parsed parameters.
    pub fn new(p: BigUint, a: BigUint, b: BigUint, q: BigUint, gx: BigUint, gy: BigUint) -> Self {
        let field_bytes = p.to_bytes_be().len();
        Curve {
            p,
            a,
            b,
            q,
            gx,
            gy,
            field_bytes,
        }
    }

    /// The generator point `P`.
    pub fn generator(&self) -> Point {
        Point::Affine {
            x: self.gx.clone(),
            y: self.gy.clone(),
        }
    }

    /// Test whether an affine point satisfies the curve equation.
    pub fn is_on_curve(&self, point: &Point) -> bool {
        match point {
            Point::Infinity => true,
            Point::Affine { x, y } => {
                let lhs = mod_mul(y, y, &self.p);
                let x3 = mod_mul(&mod_mul(x, x, &self.p), x, &self.p);
                let ax = mod_mul(&self.a, x, &self.p);
                let rhs = mod_add(&mod_add(&x3, &ax, &self.p), &self.b, &self.p);
                lhs == rhs
            }
        }
    }

    /// Point doubling.
    fn double(&self, point: &Point) -> Point {
        match point {
            Point::Infinity => Point::Infinity,
            Point::Affine { x, y } => {
                if y.is_zero() {
                    return Point::Infinity;
                }
                // lambda = (3*x^2 + a) / (2*y)
                let three = BigUint::from(3u32);
                let x2 = mod_mul(x, x, &self.p);
                let num = mod_add(&mod_mul(&three, &x2, &self.p), &self.a, &self.p);
                let den = mod_mul(&BigUint::from(2u32), y, &self.p);
                let lambda = mod_mul(&num, &mod_inv(&den, &self.p), &self.p);
                self.from_lambda(&lambda, x, y, x)
            }
        }
    }

    /// Point addition.
    pub fn add(&self, a: &Point, b: &Point) -> Point {
        match (a, b) {
            (Point::Infinity, _) => b.clone(),
            (_, Point::Infinity) => a.clone(),
            (Point::Affine { x: x1, y: y1 }, Point::Affine { x: x2, y: y2 }) => {
                if x1 == x2 {
                    // Either doubling or P + (-P) = O.
                    if y1 == y2 {
                        return self.double(a);
                    }
                    return Point::Infinity;
                }
                // lambda = (y2 - y1) / (x2 - x1)
                let num = mod_sub(y2, y1, &self.p);
                let den = mod_sub(x2, x1, &self.p);
                let lambda = mod_mul(&num, &mod_inv(&den, &self.p), &self.p);
                self.from_lambda2(&lambda, x1, y1, x2)
            }
        }
    }

    /// `x3 = lambda^2 - x_a - x_b`, `y3 = lambda*(x_a - x3) - y_a` (doubling form).
    fn from_lambda(&self, lambda: &BigUint, xa: &BigUint, ya: &BigUint, xb: &BigUint) -> Point {
        let l2 = mod_mul(lambda, lambda, &self.p);
        let x3 = mod_sub(&mod_sub(&l2, xa, &self.p), xb, &self.p);
        let y3 = mod_sub(
            &mod_mul(lambda, &mod_sub(xa, &x3, &self.p), &self.p),
            ya,
            &self.p,
        );
        Point::Affine { x: x3, y: y3 }
    }

    /// Addition form of the chord-tangent update.
    fn from_lambda2(&self, lambda: &BigUint, x1: &BigUint, y1: &BigUint, x2: &BigUint) -> Point {
        let l2 = mod_mul(lambda, lambda, &self.p);
        let x3 = mod_sub(&mod_sub(&l2, x1, &self.p), x2, &self.p);
        let y3 = mod_sub(
            &mod_mul(lambda, &mod_sub(x1, &x3, &self.p), &self.p),
            y1,
            &self.p,
        );
        Point::Affine { x: x3, y: y3 }
    }

    /// Scalar multiplication `k * point` via left-to-right double-and-add.
    pub fn scalar_mul(&self, k: &BigUint, point: &Point) -> Point {
        if k.is_zero() {
            return Point::Infinity;
        }
        let mut result = Point::Infinity;
        let bits = k.bits();
        // Process from the most-significant bit down.
        for i in (0..bits).rev() {
            result = self.double(&result);
            if k.bit(i) {
                result = self.add(&result, point);
            }
        }
        result
    }

    /// Encode a field element little-endian, padded to `field_bytes`.
    pub fn encode_coord_le(&self, value: &BigUint) -> Vec<u8> {
        let mut le = value.to_bytes_le();
        le.resize(self.field_bytes, 0);
        le
    }

    /// Encode an affine point as `X_le ‖ Y_le` (GOST raw public-key form).
    pub fn encode_point_le(&self, point: &Point) -> Option<Vec<u8>> {
        match point {
            Point::Infinity => None,
            Point::Affine { x, y } => {
                let mut out = self.encode_coord_le(x);
                out.extend_from_slice(&self.encode_coord_le(y));
                Some(out)
            }
        }
    }

    /// Decode an affine point from `X_le ‖ Y_le` (`2 * field_bytes`).
    pub fn decode_point_le(&self, bytes: &[u8]) -> Option<Point> {
        if bytes.len() != 2 * self.field_bytes {
            return None;
        }
        let x = BigUint::from_bytes_le(&bytes[..self.field_bytes]);
        let y = BigUint::from_bytes_le(&bytes[self.field_bytes..]);
        let point = Point::Affine { x, y };
        if self.is_on_curve(&point) {
            Some(point)
        } else {
            None
        }
    }
}

/// Reduce a scalar into `[1, q-1]` (rejection not needed: callers pass random
/// bytes and we reduce mod `q`, then map 0 → 1).
pub fn scalar_from_bytes_be(bytes: &[u8], q: &BigUint) -> BigUint {
    let mut k = BigUint::from_bytes_be(bytes) % q;
    if k.is_zero() {
        k = BigUint::one();
    }
    k
}

/// Whether `value` is a valid private scalar in `[1, q-1]`.
pub fn is_valid_scalar(value: &BigUint, q: &BigUint) -> bool {
    !value.is_zero() && value < q && value.gcd(q) == BigUint::one()
}

/// Parse a hex string (whitespace ignored) into a [`BigUint`].
fn from_hex(s: &str) -> BigUint {
    let cleaned: String = s.chars().filter(|c| c.is_ascii_hexdigit()).collect();
    BigUint::parse_bytes(cleaned.as_bytes(), 16).expect("valid hex constant")
}

/// `id-tc26-gost-3410-2012-256-paramSetB`.
/// OIDs: 1.2.643.7.1.2.1.1.1 and 1.2.643.2.2.35.1.
pub fn tc26_256_paramset_b() -> Curve {
    Curve::new(
        from_hex("FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD97"),
        from_hex("FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD94"),
        from_hex("A6"),
        from_hex("FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6C611070995AD10045841B09B761B893"),
        from_hex("1"),
        from_hex("8D91E471E0989CDA27DF505A453F2B7635294F2DDF23E3B122ACC99C9E9F1E14"),
    )
}

/// `id-tc26-gost-3410-2012-256-paramSetC`.
/// OIDs: 1.2.643.7.1.2.1.1.2 and 1.2.643.2.2.35.2.
pub fn tc26_256_paramset_c() -> Curve {
    Curve::new(
        from_hex("8000000000000000000000000000000000000000000000000000000000000C99"),
        from_hex("8000000000000000000000000000000000000000000000000000000000000C96"),
        from_hex("3E1AF419A269A5F866A7D3C25C3DF80AE979259373FF2B182F49D4CE7E1BBC8B"),
        from_hex("800000000000000000000000000000015F700CFFF1A624E5E497161BCC8A198F"),
        from_hex("1"),
        from_hex("3FA8124359F96680B83D1C3EB2C070E5C545C9858D03ECFB744BF8D717717EFC"),
    )
}

/// `id-tc26-gost-3410-2012-256-paramSetD`.
/// OIDs: 1.2.643.7.1.2.1.1.3 and 1.2.643.2.2.35.3.
pub fn tc26_256_paramset_d() -> Curve {
    Curve::new(
        from_hex("9B9F605F5A858107AB1EC85E6B41C8AACF846E86789051D37998F7B9022D759B"),
        from_hex("9B9F605F5A858107AB1EC85E6B41C8AACF846E86789051D37998F7B9022D7598"),
        from_hex("805A"),
        from_hex("9B9F605F5A858107AB1EC85E6B41C8AA582CA3511EDDFB74F02F3A6598980BB9"),
        from_hex("0"),
        from_hex("41ECE55743711A8C3CBF3783CD08C0EE4D4DC440D4641A8F366E550DFDB3BB67"),
    )
}

/// `id-tc26-gost-3410-2012-256-paramSetA` is a twisted-Edwards curve and is
/// rarely used for TLS server keys, so it is intentionally omitted here.
///
/// Look up a 256-bit curve by its `publicKeyParamSet` OID arcs. Returns `None`
/// for an unknown set (caller should report the OID).
pub fn curve_for_param_set(oid: &[u32]) -> Option<Curve> {
    // Legacy 2001 OIDs (1.2.643.2.2.35.x) and tc26 2012 OIDs (1.2.643.7.1.2.1.1.x).
    const A_2001: &[u32] = &[1, 2, 643, 2, 2, 35, 1];
    const B_2001: &[u32] = &[1, 2, 643, 2, 2, 35, 2];
    const C_2001: &[u32] = &[1, 2, 643, 2, 2, 35, 3];
    const XCH_A_2001: &[u32] = &[1, 2, 643, 2, 2, 36, 0];
    const XCH_B_2001: &[u32] = &[1, 2, 643, 2, 2, 36, 1];
    const B_2012: &[u32] = &[1, 2, 643, 7, 1, 2, 1, 1, 1]; // tc26 paramSetB
    const C_2012: &[u32] = &[1, 2, 643, 7, 1, 2, 1, 1, 2]; // tc26 paramSetC
    const D_2012: &[u32] = &[1, 2, 643, 7, 1, 2, 1, 1, 3]; // tc26 paramSetD
    match oid {
        o if o == A_2001 || o == XCH_A_2001 || o == B_2012 => Some(tc26_256_paramset_b()),
        o if o == B_2001 || o == XCH_B_2001 || o == C_2012 => Some(tc26_256_paramset_c()),
        o if o == C_2001 || o == D_2012 => Some(tc26_256_paramset_d()),
        _ => None,
    }
}

#[cfg(test)]
pub(crate) mod tests_support {
    use super::*;

    /// Parse a whitespace-delimited big-endian hex blob (as copied from an RFC).
    pub(crate) fn hx(s: &str) -> BigUint {
        let cleaned: String = s.chars().filter(|c| c.is_ascii_hexdigit()).collect();
        BigUint::parse_bytes(cleaned.as_bytes(), 16).expect("valid hex")
    }

    /// The 512-bit `id-tc26-gost-3410-12-512-paramSetA` curve (RFC 7836 App. A.1).
    pub(crate) fn paramset_a_512() -> Curve {
        let p = hx("00 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
             FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
             FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
             FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FD
             C7");
        let a = hx("00 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
             FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
             FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
             FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FD
             C4");
        let b = hx("00 E8 C2 50 5D ED FC 86 DD C1 BD 0B 2B 66 67 F1
             DA 34 B8 25 74 76 1C B0 E8 79 BD 08 1C FD 0B 62
             65 EE 3C B0 90 F3 0D 27 61 4C B4 57 40 10 DA 90
             DD 86 2E F9 D4 EB EE 47 61 50 31 90 78 5A 71 C7
             60");
        let q = hx("00 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
             FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
             FF 27 E6 95 32 F4 8D 89 11 6F F2 2B 8D 4E 05 60
             60 9B 4B 38 AB FA D2 B8 5D CA CD B1 41 1F 10 B2
             75");
        let gx = hx("03");
        let gy = hx("75 03 CF E8 7A 83 6A E3 A6 1B 88 16 E2 54 50 E6
             CE 5E 1C 93 AC F1 AB C1 77 80 64 FD CB EF A9 21
             DF 16 26 BE 4F D0 36 E9 3D 75 E6 A5 0E 3A 41 E9
             80 28 FE 5F C2 35 F5 B8 89 A5 89 CB 52 15 F2 A4");
        Curve::new(p, a, b, q, gx, gy)
    }
}

#[cfg(test)]
mod tests {
    use super::tests_support::paramset_a_512;
    use super::*;

    #[test]
    fn generator_is_on_curve() {
        let c = paramset_a_512();
        assert!(c.is_on_curve(&c.generator()));
    }

    #[test]
    fn scalar_mul_distributes_over_addition() {
        let c = paramset_a_512();
        let g = c.generator();
        // (2G) + (3G) == 5G
        let g2 = c.scalar_mul(&BigUint::from(2u32), &g);
        let g3 = c.scalar_mul(&BigUint::from(3u32), &g);
        let g5a = c.add(&g2, &g3);
        let g5b = c.scalar_mul(&BigUint::from(5u32), &g);
        assert_eq!(g5a, g5b);
        assert!(c.is_on_curve(&g5a));
    }

    #[test]
    fn scalar_mul_by_q_is_infinity() {
        let c = paramset_a_512();
        let qg = c.scalar_mul(&c.q.clone(), &c.generator());
        assert_eq!(qg, Point::Infinity);
    }

    #[test]
    fn point_le_roundtrips() {
        let c = paramset_a_512();
        let g2 = c.scalar_mul(&BigUint::from(2u32), &c.generator());
        let bytes = c.encode_point_le(&g2).unwrap();
        assert_eq!(bytes.len(), 2 * c.field_bytes);
        let back = c.decode_point_le(&bytes).unwrap();
        assert_eq!(g2, back);
    }

    #[test]
    fn tc26_256_generators_on_curve_and_prime_order() {
        for c in [
            tc26_256_paramset_b(),
            tc26_256_paramset_c(),
            tc26_256_paramset_d(),
        ] {
            assert_eq!(c.field_bytes, 32, "256-bit field");
            assert!(c.is_on_curve(&c.generator()), "generator must lie on curve");
            // q * G == O proves the published subgroup order matches the generator.
            assert_eq!(
                c.scalar_mul(&c.q.clone(), &c.generator()),
                Point::Infinity,
                "q*G must be the identity"
            );
        }
    }

    #[test]
    fn curve_lookup_resolves_known_param_sets() {
        assert_eq!(
            curve_for_param_set(&[1, 2, 643, 2, 2, 35, 1]),
            Some(tc26_256_paramset_b())
        );
        assert_eq!(
            curve_for_param_set(&[1, 2, 643, 7, 1, 2, 1, 1, 1]),
            Some(tc26_256_paramset_b())
        );
        assert_eq!(
            curve_for_param_set(&[1, 2, 643, 2, 2, 35, 2]),
            Some(tc26_256_paramset_c())
        );
        assert_eq!(
            curve_for_param_set(&[1, 2, 643, 2, 2, 35, 3]),
            Some(tc26_256_paramset_d())
        );
        assert_eq!(curve_for_param_set(&[1, 2, 643, 99]), None);
    }
}
